### ISSUE TITLE
Word wrapping doesn't seem to work properly

### ISSUE THREAD

**Issue by alexlyzhov** [safoex/skoltech_thesis_template#1]
After I upload the project to overleaf according to the instruction (XeLaTeX and fonts in place) and compile, I get several `Overfull \hbox` and `Underfull \hbox` errors and word wrapping doesn't work in some places (e.g. in Russian abstract) - the text gets on top of what should be whitespace.

**Comment by alexlyzhov** [comment]
Seems like `\selectlanguage{russian}` works if I place it before Russian text (credits to Alexander Zozulya) and `\linebreak` works in some other places with formulas, long words and `\texttt` commands (credits to Artem Sevastopolsky)

**Comment by safoex** [comment]
Thank you for noticing! 
Another workaround is to add `\sloppy` in the beginning of the chapter. It leaves an underfull warning sometimes, so I commited `\selectlanguage{russian}` solution.
